# Generated by Django 5.2.7 on 2025-10-09 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("start_time", models.DateField(auto_now=True)),
                ("end_time", models.DateField(blank=True, null=True)),
                ("duration", models.IntegerField()),
                (
                    "timer_type",
                    models.CharField(
                        choices=[("WORK", "Work timer"), ("BREAK", "Break timer")],
                        max_length=64,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
        ),
    ]
