# Generated by Django 5.2.7 on 2025-10-14 12:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prayer", "0001_initial"),
        ("timer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=250)),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrayerPlanting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plantings",
                        to="plant.plant",
                    ),
                ),
                (
                    "prayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plantings",
                        to="prayer.prayer",
                    ),
                ),
                (
                    "timer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plantings",
                        to="timer.timer",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
        ),
    ]
